#!/usr/bin/env node
/**
 * Pulls the site's visual identity into the portal at build time.
 *
 * The portal must look like a sibling of lorenzo.loconsole.eu, but copying the
 * site's colours into the portal would drift the first time either changed.
 * So the site's own files stay the single source of truth and this derives
 * everything from them:
 *
 *   static/css/main.css   -> src/lib/brand/brand.css  (@font-face + theme tokens)
 *   static/fonts/*.woff2  -> static/brand/fonts/
 *   static/img/logo.svg   -> static/brand/logo.svg
 *   static/img/favicon.*  -> static/brand/
 *
 * Runs as predev and prebuild. The output is gitignored; the Docker build uses
 * the repository root as its context precisely so this can reach ../static.
 */
import fs from 'node:fs';
import path from 'node:path';

const ADMIN = path.resolve(import.meta.dirname, '..');
const SITE = path.resolve(ADMIN, '..');
const CSS_IN = path.join(SITE, 'static', 'css', 'main.css');
const CSS_OUT = path.join(ADMIN, 'src', 'lib', 'brand', 'brand.css');
const ASSETS_OUT = path.join(ADMIN, 'static', 'brand');

/**
 * Returns the full `selector { … }` block, matching braces properly.
 * @param {string} css
 * @param {RegExp} selectorRe
 * @returns {string | null}
 */
export function extractBlock(css, selectorRe) {
	const m = selectorRe.exec(css);
	if (!m) return null;
	let depth = 0;
	for (let i = m.index; i < css.length; i++) {
		if (css[i] === '{') depth++;
		else if (css[i] === '}') {
			depth--;
			if (depth === 0) return css.slice(m.index, i + 1);
		}
	}
	return null;
}

/**
 * @param {string} css
 * @returns {string[]}
 */
export function extractFontFaces(css) {
	/** @type {string[]} */
	const out = [];
	const re = /@font-face\s*\{[^}]*\}/g;
	let m;
	while ((m = re.exec(css))) out.push(m[0]);
	return out;
}

/**
 * @param {string} css
 * @returns {string}
 */
export function buildBrandCss(css) {
	const faces = extractFontFaces(css).map((f) => f.replace(/url\(\/fonts\//g, 'url(/brand/fonts/'));
	// The light tokens live in the :root block that defines --background; the
	// dark ones in [data-theme="dark"].
	const light = extractBlock(css, /:root\s*\{(?=[^}]*--background)/);
	const dark = extractBlock(css, /\[data-theme="dark"\]\s*\{/);
	if (!light || !dark) throw new Error('could not find the :root and [data-theme="dark"] token blocks in main.css');
	if (faces.length === 0) throw new Error('no @font-face rules found in main.css');

	return [
		'/* GENERATED by scripts/sync-brand.mjs from ../static/css/main.css.',
		'   Do not edit: change the site, and the portal follows on its next build. */',
		'',
		...faces,
		'',
		light,
		'',
		dark,
		''
	].join('\n');
}

/**
 * @param {string} from
 * @param {string} to
 */
function copy(from, to) {
	fs.mkdirSync(path.dirname(to), { recursive: true });
	fs.copyFileSync(from, to);
}

if (import.meta.url === `file://${process.argv[1]}`) {
	if (!fs.existsSync(CSS_IN)) {
		console.error(`sync-brand: ${CSS_IN} not found — is the build running from the repo root?`);
		process.exit(1);
	}
	const css = fs.readFileSync(CSS_IN, 'utf8');
	fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
	fs.writeFileSync(CSS_OUT, buildBrandCss(css));

	const fontsIn = path.join(SITE, 'static', 'fonts');
	let fonts = 0;
	for (const f of fs.readdirSync(fontsIn)) {
		if (!f.endsWith('.woff2')) continue;
		copy(path.join(fontsIn, f), path.join(ASSETS_OUT, 'fonts', f));
		fonts++;
	}
	for (const f of ['logo.svg', 'favicon.png', 'favicon.svg', 'favicon.ico']) {
		const src = path.join(SITE, 'static', 'img', f);
		if (fs.existsSync(src)) copy(src, path.join(ASSETS_OUT, f));
	}
	console.log(`sync-brand: ${fonts} fonts, logo and favicons, tokens from main.css`);
}
